spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties.hibernate:
      show_sql: true
      format_sql: true
    open-in-view: false
  data:
    web.pageable.default-page-size: 20
  quartz:
    job-store-type: memory

logging.file.path: src/main/resources/log

server:
  port: 8080
  servlet:
    context-path: /api

cluster:
  shards:
    1:
      8081: first-app
      8082: second-app
      8083: third-app
    2:
      8084: fourth-app
      8085: fifth-app
      8086: sixth-app
    0:
      8087: seventh-app
      8088: eighth-app
      8089: ninth-app
  allNodes:
    8081: first-app
    8082: second-app
    8083: third-app
    8084: fourth-app
    8085: fifth-app
    8086: sixth-app
    8087: seventh-app
    8088: eighth-app
    8089: ninth-app
  schedulerStartDelay: 10_000
  schedulerRepeatInterval: 180_000
